import type { Metadata, Viewport } from 'next'

import { Inter_Tight, Geist_Mono } from 'next/font/google'
import './globals.css'

const interTight = Inter_Tight({ variable: '--font-inter-tight', subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sound Wave',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' suppressHydrationWarning className='dark'>
      <body className={`${interTight.variable} ${geistMono.variable} antialiased bg-[#1b1d21]`}>{children}</body>
    </html>
  )
}

